name: Build & release
on: push

jobs:
  build:
    name: Build typst document
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Chinese fonts
        run: |
          wget https://github.com/notofonts/noto-cjk/releases/download/Serif2.003/09_NotoSerifCJKsc.zip
          unzip 09_NotoSerifCJKsc.zip -x LICENSE
      - uses: typst-community/setup-typst@v3
      - run: typst compile --font-path OTF/SimplifiedChinese slides.typ
      - uses: actions/upload-artifact@v4
        with:
          name: slides
          path: slides.pdf
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
        with:
          files: slides.pdf
